### ISSUE TITLE
Close the session when any of the buffers is deleted

### ISSUE THREAD

**Issue by odnoletkov** [bfrg/vim-jqplay#1]
Currently the session closes automatically only when the source buffer is removed. My mental model for the session is it supports a connection between three buffers. When any of the buffers is deleted it doesn't make much sense to keep the session.

The argument can be made that a session with only source and output buffers could be useful – when the filter is complete and won't change anymore. But I think it is quite an edge case and can be ignored for simplicity.

**Comment by bfrg** [comment]
The session is closed if _any_ of the three buffers (`jq` filter, `json` input, `json` output) is deleted or wiped out. By **session is closed** I mean, the connection between the three buffers is removed, and `jq` won't be invoked anymore when input or filter buffer is modified.

Running `:bdelete` or `:bwipeout` won't remove the other buffers. Those are built-in commands that delete or wipe out the current buffer only. I don't think it's wise to change that. When you delete or wipe out a buffer, this means (to me) you don't need this particular buffer anymore, but you might still want to work with the others.

I think what you want is `:JqplayClose!`. This command will close the session (i.e. remove the connection between the buffers, stop any running `jq` process, and remove the autocommands that automatically invoke `jq`). It will also delete the `jq` filter buffer and the `json` output buffer. Since `:Jqplay` needs to be called on an already opened `json` buffer, this buffer will remain open.

There's a command in the examples `:JqplayScratch`. You can run it from anywhere. It will open a new `json` scratch buffer. When you're done, you can run `:JqplayClose!`, and it will close the `jq` filter buffer and the `json` output buffer. The `json` scratch buffer will nevertheless remain open. I can add a more sophisticated example that will also remove the `json` scratch buffer. I think that's what you want?

Maybe I should add `:JqplayScratch` to the plugin and not just mention it in the README and in `:h jqplay-faq`?

**Comment by odnoletkov** [comment]
Thanks for the explanation. Now I see that actually *deleting* filter or output buffers does indeed close the session.

What confused me originally is that *closing the window* for these buffers didn't remove the buffer – and therefore didn't close the Jqplay session. I don't use `set hidden` so this behaviour is unexpected to me.

Is there any specific reason why you force the `set bufhidden=hide` in these buffers?

The rest of what you explained makes perfect sense to me and I don't ask for any changes there.

**Comment by bfrg** [comment]
With `setlocal bufhidden=hide` the buffer won't be unloaded when the window is closed. If you unload a scratch buffer (a buffer with `setlocal buftype=nofile`), its content will be gone. Note: The buffer is just unloaded but it is neither deleted nor wiped out.

Imagine someone spends over an hour to write a filter and accidentally closes that window. You will be able to reopen the buffer, but it will be empty.

**Comment by bfrg** [comment]
The quickest way to close everything is with `:JqplayClose!`. I have modified it to delete the input buffer as well when it's a scratch buffer (buffer with `buftype=nofile`).

**Comment by odnoletkov** [comment]
I see. It's a shame there is no way to have `nofile` behaviors and prevent the user from accidentally closing the buffer and loosing it's content.

Will use the `:JqplayClose` command to close the session.

**Comment by bfrg** [comment]
You can always override buffer-local options. For example:
```vim
" in your vimrc
augroup jqplay-custom
    autocmd!
    autocmd FileType json
            \ if bufname('%') =~# '^jq-output' |
            \   setlocal bufhidden=            |
            \ endif
    autocmd FileType jq
            \ if bufname('%') =~# '^jq-filter' |
            \   setlocal bufhidden=            |
            \ endif
augroup END
```
Or alternatively, if you use `ftplugin` files:
```vim
" in after/ftplugin/json.vim
if bufname('%') =~# '^jq-output'
    setlocal bufhidden=
endif

" in after/ftplugin/jq.vim
if bufname('%') =~# '^jq-filter'
    setlocal bufhidden=
endif
```
But as I said above, this will just _unload_ the buffers. If I understand you correctly, you want to close the session including all associated buffers when one of the windows is closed?

**Comment by odnoletkov** [comment]
> you want to close the session including all associated buffers when one of the windows is closed?

Not exactly. I wanted to close *only the session* when *any* of its windows is closed. I didn't want to close or do anything with other windows and buffers. This was the behaviour I've seen – but only for the *input* buffer. So I thought if this works for the input buffer – why not for filter and output as well?

And I've just realized that this behavior for the input buffer happens only in certain cases. I was opening the Vim reading json on the stdin:
```
$ some_program_producing_json | vim -
:Jqplay
```
In this case closing the input window closes the jqplay session.

If I just open existing json file and `:Jqplay` from it there is no such behavior – session doesn't close when I close the input buffer's window.

In the end I think your point about protecting users from accidentally loosing filter's buffers content is most important – so force-hiding supplementary buffers is the least of all evils.
